### ISSUE TITLE
Automated tests not working in Wk 4 milestone because MySQL isn't being started

### ISSUE THREAD

**Issue by euangeleo** [Abhi291712/PROJECT_508#1]
It looks like you're trying to get the Pytest tests to run whenever you push to GitHub. This would be great! Your MySQL tests are failing, though, because your GitHub Action doesn't know that it needs to start up your MySQL service docker image. Compare what you have here to what's in the Week 4 programming assignment to see how to tell GitHub that, before it runs the Pytest tests, it needs to also grab a MySQL container image, start that up in a container, and then connect to that image on the right interface. (In PA4, note that instead of 'localhost' in `db/mysql_repository.py`, the value for 'host' is 'mysql', which corresponds to this line in `.github/workflows/ci.yml`:

```
docker run -i --network ${{ job.services.mysql.network }} ${ORG}/${IMAGE_NAME}:${TAG} python -m pytest tests
```

Here, you're telling Docker to run the tests (in a container from `uazhlt/ling-508-pa-week4:latest`) on whatever the network is for `${{job.services.mysql.network}}`, which is the interface named 'mysql' . See [this page](https://docs.docker.com/reference/cli/docker/container/run/#network) for info on the `docker run` command.

Getting your tests and MySQL database running on GitHub would be great, however, you don't need to get that done before the course ends. You might want to focus more on your service layer for week 5. I recommend that you work on getting the tests working on GitHub ONLY if you have time this week!

**Comment by Abhi291712** [comment]
Thanks for your feedback.
